services:
  - type: web
    name: nintendo-rag-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: EMBEDDING_MODEL
        value: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2